services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        image: outages-bot:latest
        container_name: outages-bot
        command: ["php", "bin/console", "app:bot"]
        user: "1000:1001"
        env_file:
            - .env
            - .env.dev
            - .env.local
        volumes:
            - ./:/app
            - ./data:/app/data
        restart: unless-stopped

    notifier:
        image: outages-bot:latest
        depends_on:
            - bot
        container_name: outages-bot-notifier
        command: ["supercronic", "/app/crontab"]
        user: "1000:1001"
        env_file:
            - .env
            - .env.dev
            - .env.local
        volumes:
            - ./:/app
            - ./data:/app/data
        restart: unless-stopped
