services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    SergiX44\Nutgram\Nutgram:
        arguments:
            $token: '%env(TELEGRAM_BOT_TOKEN)%'

    App\Infrastructure\Repository\FileUserRepository:
        arguments:
            $params: '@parameter_bag'

    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'
